name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install Nim
        run: curl -sSf https://nim-lang.org/choosenim/init.sh | sh -s -- -y

      - name: build Actually Portable Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH && make

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: portablenim
          path: './portablenim.com'
          if-no-files-found: error

  testLinux:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: portablenim

      - name: Remove Mono
        run: sudo apt remove --purge --auto-remove mono-runtime

      - name: Test on Linux
        run: chmod +x portablenim.com && ./portablenim.com

  testWindows:
    needs: setup
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: portablenim

      - name: Test on Windows
        run: ${{steps.download.outputs.download-path}}/portablenim.com
